"""
Django settings for App project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv

# 1. Definición de la ruta base del proyecto
# ----------------------------------------
# Path(__file__)                           -> Objeto Path que apunta a settings.py.
# Path(__file__).resolve()                 -> Obtiene la ruta absoluta (completa) del archivo settings.py.
# Path(__file__).resolve().parent          -> Sube un nivel, apuntando a la carpeta 'proyecto'.
# Path(__file__).resolve().parent.parent   -> Sube otro nivel, apuntando a la carpeta raíz 'backDjango'.
# Esto es necesario porque el archivo .env está en 'backDjango', no en 'proyecto'.
# 1. Definición de la ruta base del proyecto
# ----------------------------------------
# Path(__file__).resolve().parent.parent.parent apunta a la raíz 'SistemaProyecto'
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# 2. Cargar las variables de entorno
# ----------------------------------
# BASE_DIR / '.env'                        -> Construye la ruta completa: 'backDjango/.env'.
# load_dotenv(...)                         -> Lee ese archivo '.env' y carga las variables (DB_HOST, DB_USER, etc.)
#                                            en el entorno de ejecución de Python.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v=y$a5pnquhp$g$pf8l+igc9smqnyq2+o-y4v7j@&2@00oc@lv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',   #para las apis
    'corsheaders',      #permite la comunicación con react
    'inventario',       #nombre de la app
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  #al incluirse dos direcciones nos aseguramos de que django acepte la solicitud sin importar qué nombre o IP haya usado el frontend de React para identificarse ante el backend
    'http://127.0.0.1:3000'
]

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        
        # Leído de .env
        'NAME': os.getenv('DB_NAME'), 
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        
        # CRÍTICO: Supabase requiere conexión segura (SSL)
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
